services:
    search_engine:
        image: neonmmd/websurfx:redis
        ports:
            - 8000:8080
        depends_on:
            - redis
        # links:
        #     - redis
        volumes:
            - ./websurfx/:/etc/xdg/websurfx/
    redis:
        image: redis:latest
