name: Container
on: 
  # push:
  workflow_dispatch:
jobs:
  Sync:
    runs-on: ubuntu-latest
    env:
      HF_HUB_ENABLE_HF_TRANSFER: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      